
test:
	gcc -g -I../includes -I../libft ../libft/libft.a ./bfirst_search.c

all:
	gcc visualiser.c -g anthill.c -lSDL2 -lSDL2_gfx draw*.c read_input.c -I../includes -I../libft ../libft/libft.a ./bfirst_search.c

